### ISSUE TITLE
The channel cannot be released after hanging up

### ISSUE THREAD

**Issue by 2954456878** [amigniter/mod_audio_stream#35]
I can reproduce this problem：
1.bgapi originate {origination_uuid=1234567899}user/1002 &playback(/usr/local/freeswitch/sounds/music/8000/suite-espanola-op-47-leyenda.wav)
2.uuid_audio_stream 123456789 start ws://127.0.0.1:9399/webrtc/uuid mono 8000
3.uuid_kill 123456789 
4.show channels:
123456789,outbound,2024-06-28 14:27:00,1719556020,sofia/internal/1002@127.0.0.1:43096,CS_EXECUTE,Outbound Call,1002,,1002,playback,/usr/local/freeswitch/sounds/music/8000/suite-espanola-op-47-leyenda.wav,,default,PCMA,8000,64000,PCMA,8000,64000,,iZ8vb4brpkx721d11r16tjZ,1002@172.29.238.179,,1002,ACTIVE,,0000000000,RECV,1234567891,,,,0000000000,,1002,,default

But in the middle of step 2 and step 3 execute: uuid_audio_stream 123456789 stop ws://127.0.0.1:9399/webrtc/uuid mono 8000，the channel will be released normally

**Comment by 2954456878** [comment]
FreeSWITCH Version 1.10.10-release~64bit ( 64bit)

**Comment by amigniter** [comment]
You're right. The latest commit was incomplete and caused the issue. It has been fixed. Thanks for pointing it out.

**Comment by chinarui-na** [comment]
I got it back. The channel's still on

**Comment by boteman** [comment]
FYI, this *might* be related to the FreeSWITCH deadlock/zombie channels tickets which requires a deep dive into the low-level code. No ETR yet.
These are some of the related tickets:
https://github.com/signalwire/freeswitch/issues/2290
https://github.com/signalwire/freeswitch/issues/2389
https://github.com/signalwire/freeswitch/pull/2387

**Comment by remcovanvugt** [comment]
Tried the latest main from FreeSWITCH with the issues @boteman mentioned but this still happened. Found the issue and filed a PR  https://github.com/amigniter/mod_audio_stream/pull/62
